### ISSUE TITLE
A way to transform the inputs of a combiner without writing to disk?

### ISSUE THREAD

**Issue by USER-5** [rabitt/pysox#100]
I need to audio files at specified SNR levels, I've found that I can normalise the audio to 0dB & set the gain etc. using the transform class and build, then mix them using the combiner class & build a second time.

Is there any way I could do this without the intermediate step of writing the files to disk?
I need to automate this process for thousands of files & need all the efficiency I can get...

**Comment by lostanlen** [comment]
Hello, can you describe your exact pipeline at the moment?
If I/O is an issue, i recommend using librosa for normalizing to 0dB and doing the mixing in terms of numpy arrays.

**Comment by USER-5** [comment]
Currently I create a transform class with:
```python
tfm = sox.Transformer()
tfm.norm(db_level=0.0)
tfm.convert(samplerate=16000,n_channels=1,bitdepth=32)
tfm.build('Input1.wav','Intermediate1.flac')
tfm.build('Input2.flac','Intermediate2.flac')

volume1 = 0.5 #example
volume2 = 0.5

cbn = sox.Combiner()
cbn.build(['Intermediate1.flac','Intermediate2.flac'],\
          'output.flac',\
          'mix',\
          input_volumes=[volume1,volume2])
```
I was just hoping that there would be a way to avoid writing (and then later on deleting) these intermediate files?
Otherwise my best approach is probably to pass over all the input files, and normalise them to 0dB, and remove the originals. Then combine them in a separate pass.

**Comment by lostanlen** [comment]
Thank you for clarifying. I think that sox does not support this. Therefore, it is out of scope of pysox.

Coincidentally, the pipeline you describe is comparable to what scaper does. Please see:
https://github.com/justinsalamon/scaper/blob/master/scaper/core.py#L1640

Note that pysox uses temporary files to do the transformations before the combination.

Here's a librosa script which does what you want:

```
y1, _ = librosa.load("Input1.wav", sr=16000, mono=True)
y1_normalized = y1 / np.max(librosa.rmse(y1))
volume1 = 0.5

y2, _ = librosa.load("Input2.wav", sr=16000, mono=True)
y2_normalized = y2 / np.max(librosa.rmse(y2))
volume2 = 0.5

y_mix = volume1 * y1_normalized + volume2 * y2_normalizeed
```

Then use `soundfile.write` to export.
I hope this helps!
