### ISSUE TITLE
32 bit floating point

### ISSUE THREAD

**Issue by qo4on** [rabitt/pysox#111]
Is it possible to get 32 bit floating point before pitch and in final `wav` from `mp3` with Pysox?
```
sox "0.mp3" -b 32 -e float "0.wav" rate -v 48k pitch 50
```

**Comment by rabitt** [comment]
Yes, you can use `tfm.set_output_format`.

**Comment by tensorfoo** [comment]
@rabitt - i just tried this out and i'm still getting integers: 
 ```
     tfm = sox.Transformer()
     tfm.set_output_format(rate=16000, channels=1, encoding="floating-point")
     return tfm.build_array(filename)
```

**Comment by jbmaxwell** [comment]
I'm having the same issue. Did you work this out, @tensorfoo?
