### ISSUE TITLE
Duration changes on saving

### ISSUE THREAD

**Issue by qo4on** [rabitt/pysox#112]
When I open [this mp3 file](https://www.dropbox.com/s/j5289g12gr2i1de/03-01-01-01-01-01-01.mp3) and save it to wav its duration becomes 0.024 sec shorter. Is it a bug?
![image](https://user-images.githubusercontent.com/35609308/85779568-2a5f5400-b73d-11ea-8554-5f51fe181c3b.png)

**Comment by rabitt** [comment]
No, I don't believe this is a bug. Converting between file formats can result in small differences in duration.

**Comment by qo4on** [comment]
I found the solution. `mpg123` can open `mp3` file and save to `wav` keeping the duration unchanged.
