### ISSUE TITLE
sox FAIL formats: can't open input `test.wav': WAVE: RIFF header not found

### ISSUE THREAD

**Issue by Adekiii** [rabitt/pysox#113]
Hi, with this simple script I'm trying to apply the reverb effect to a .wav file:

```
def reverb():
    tfm = sox.Transformer()
    tfm.reverb()
    tfm.build('test.wav', 'reverb.wav')
```

However, it returns an error message saying RIFF header not found.

**Comment by rabitt** [comment]
I don't think it is an issue with pysox necessarily - most likely your wav file is missing header data. One thing you can try is explicitly setting the input format (`tfm.set_input_format`) with the sample rate, file type, and bit rate.

Closing this issue, but feel free to reopen if you find it's a general problem with pysox.
