### ISSUE TITLE
Could you please tag releases on github?

### ISSUE THREAD

**Issue by MeggyCal** [rabitt/pysox#115]
I am a packager and we love to launch tests wherever it is possible. I downloaded your PyPI tarball, but the tests are broken in there (no test data). I see it does not make sense to ship test data on PyPI, but could you please at least tag the releases on github so I could download the complete tarball? Thanks a lot!

**Comment by rabitt** [comment]
@MeggyCal yes sure. I've just published a release for 0.4.0
