### ISSUE TITLE
sox.Transform().build cannot set output path to None

### ISSUE THREAD

**Issue by mungsoo** [rabitt/pysox#121]
Hi,

I'm trying to use sox to pipe the output directly to the memory instead write to a file, I read the doc string which says "If output_filepath is None, return_output=True by default.". But it raise an error when I set output_filepath to None.

I also tried to edit the build method to make it compatible with my usecase, but it seems the way it calls sox and pass  args to sox won't allow pipe output only. 

Any help is really appreciated!

**Comment by rabitt** [comment]
Hello @mungsoo 

Can you send the exact command you're sending? You can use `tfm.build`, but now we recommend using [`tfm.build_array`](https://pysox.readthedocs.io/en/latest/api.html#sox.transform.Transformer.build_array) if you want to output to memory instead of a file.

**Comment by rabitt** [comment]
Closing this for now, but feel free to reopen if you find a bug!
