### ISSUE TITLE
Documentation not showing for version: latest

### ISSUE THREAD

**Issue by ArthurKwok** [rabitt/pysox#134]
Hi Rachel!

I'm just checking the documentation, it seems that https://pysox.readthedocs.io/en/latest/api.html is not showing anything. The other versions, including v:stable, seem to be fine.

Best,
Arthur Guo

**Comment by rabitt** [comment]
Thanks for flagging this @ArthurKwok ! Looking into this now

**Comment by rabitt** [comment]
This should be fixed now, please reopen if not!
