### ISSUE TITLE
Tagged releases are out of sync with PyPi

### ISSUE THREAD

**Issue by jgarte** [rabitt/pysox#148]
Hi, is it possible to tag releases here so they are in sync with the version that's on PyPi?

This would help avoid confusion when packaging for distros.

https://issues.guix.gnu.org/49469

**Comment by lostanlen** [comment]
Hello, what should we do exactly?

**Comment by jgarte** [comment]
> Hello, what should we do exactly?

1. Add the [data files folder](https://github.com/rabitt/pysox/tree/master/tests/data) for tests on pypi. PyPi includes the test folder but without the data files folder tests fail.

2. The version on PyPi should be the same as the version on the github releases. Version on PyPi is 1.4.1 and version on github releases is 0.4.0

**Comment by jgarte** [comment]
Thanks for the reply.

> 1. it's not obvious that we should do this. PyPI releases are application-oriented and typically do not include unit tests at all. If you need to run your own unit tests, you can use the GitHub link.

Then the test folder should probably be removed from the PyPi tarball since it will fail without the data folder containing the audio files. It becomes confusing to have it there unless upstream is expecting the users to run a subset of tests that don't use the audio files for testing?

> 2. ... Possible release a 1.5.0 both on GitHub and PyPI?

Yup. Just to have them in sync with each other.

**Comment by lostanlen** [comment]
Agreed with 1. We need green light from @rabitt for 2.

**Comment by rabitt** [comment]
> Agreed with 1. We need green light from @rabitt for 2.

I'm OK with a 1.5.0 release to sync the two. I have on my backlog to set up GH actions to automatically push pypi releases when a github release is tagged which should solve this problem moving forward.

**Comment by lostanlen** [comment]
1.5.0-rc1 is out on PyPI
https://pypi.org/project/sox/1.5rc1/
