### ISSUE TITLE
Extract a song into multitrack wav files

### ISSUE THREAD

**Issue by romino666** [rabitt/pysox#152]
@rabitt If i can import a michael jackson song in mp3 format, can i convert a song into a multitrack wav file with 96 tracks ?

**Comment by lostanlen** [comment]
You can convert from MP3 to WAV with appropriate codecs, but i don't see how that could end up being multitrack.

**Comment by romino666** [comment]
We can search a solution to extract a song into multitracks wav files, OK?

**Comment by lostanlen** [comment]
This is documented here: https://github.com/rabitt/pysox#examples
