### ISSUE TITLE
Disable warnings when overwriting output file

### ISSUE THREAD

**Issue by justinsalamon** [rabitt/pysox#25]
There are scenarios where you know in advance that you're going to use pysox to overwrite an existing file, e.g. when using temporary files like in [this example](https://github.com/rabitt/pysox/issues/6#issuecomment-251792138) from #6. In this situation it's inconvenient to have pysox issue a warning for every file overwrite (as there are many), and right now there's no way to disable these warnings in pysox (you can hack it by changing the logging level as in the example provided above, but that's not ideal).

It would be nice to have an optional flag in pysox (or maybe at the transformer/combiner level?) to disable file overwrite warnings (and maybe another option to disable all warnings from pysox?).

**Comment by rabitt** [comment]
@justinsalamon this is fixed as of version 1.3.2 . See #51 

The default logging level is now `WARNING` which will still show the overwrite warnings. You can change this in your environment by calling, for example:
```python
logging.getLogger('sox').setLevel(logging.ERROR)
```
