### ISSUE TITLE
Return transformer and combiner always?

### ISSUE THREAD

**Issue by carlthome** [rabitt/pysox#4]
Just a proposal for the API, it would be neat if all methods in `Transformer` and `Combiner` return `self`, so that one could create chains like this:

```Python
import sox
tfm = sox.Transformer('path/to/input_audio.wav', 'path/to/output/audio.aiff')
         .trim(5, 10.5)
         .compand()
         .fade(fade_in_len=1.0, fade_out_len=0.5)
         .build()
```
[(reference)](https://en.wikipedia.org/wiki/Fluent_interface)

**Comment by ejhumphrey** [comment]
ooooh I like it -- +1!

**Comment by rabitt** [comment]
Awesome idea!

**Comment by rabitt** [comment]
Done as of 1.1.9
