### ISSUE TITLE
transformer.stat returns dictionary with unclear structure

### ISSUE THREAD

**Issue by tomxi** [rabitt/pysox#59]
transformer.stat returns a dictionary. However in the documentation, the structure (i.e., keys) of the dictionary is not specified in the documentation.

**Comment by rabitt** [comment]
Unfortunately, depending on the installed version of SoX, the information returned by stat is completely different, so I chose to leave the specific details out of the documentation. Happy to hear if you have ideas for how to fix this though!

**Comment by tomxi** [comment]
I think that's fine... there are ways to print the keys of a dictionary. I'm gonna close this issue.
