### ISSUE TITLE
Is the output format automatically applied according to extension specified in build?

### ISSUE THREAD

**Issue by Zerokami** [rabitt/pysox#64]
I'm trying to use pysox for a django app.

I want to know if I just need to specify the output extension in `.build` to get the desired output format.

**Comment by rabitt** [comment]
@Logmytech apologies for the slow answer to your question.

By default, the audio file type is determined by the file extension of `output_filepath`. However, if you call `Transformer. set_output_format()` and specify a file type, SoX will write the specified file type.

**Comment by rabitt** [comment]
For example:
```
import sox
tfm = sox.Transformer()
tfm.build("input.wav", "output.mp3")
```
converts the file "input.wav" to an mp3 file called "output.mp3"

```
import sox
tfm = sox.Transformer()
tfm.set_output_format(file_type='ogg')
tfm.build("input.wav", "output")
```
converts the file "input.wav" to an (extensionless) ogg file called "output"

finally,
```
import sox
tfm = sox.Transformer()
tfm.set_output_format(file_type='flac')
tfm.build("input.wav", "output.wav")
```
this works, and rather unintuitively converts "input.wav" to a flac file called "output.wav". Obviously not recommended, but possible.
