### ISSUE TITLE
Trying to use the core API play.

### ISSUE THREAD

**Issue by tkamaal** [rabitt/pysox#70]
Hello, 

I'm trying to play music through sox. For this purpose, I'm using the play API available in core.py. But I get the following error **OSError: Play failed! [WinError 2] The system cannot find the file specified** 

`     retval = os.getcwd()

    INPUT_FILE = os.path.join(retval + '\\BG\\test.wav')

    print(INPUT_FILE)

    arg_list = ['play', music_file]

    handler = core.play(arg_list)  
`

Please, provide an example use case of core.play() API.

**Comment by rabitt** [comment]
Hey @tkamaal 

Right now `play` is (somewhat opaquely) wrapped inside the `preview()` method of the `Transformer` and `Combiner` classes.

A minimal example would be:
```
import sox
tfm = sox.Transformer()
tfm.preview("path_to_a_file.wav")
```

any number of effects can be applied and previewed as well:
```
import sox
tfm = sox.Transformer()
tfm.reverb()
tfm.reverse()
tfm.preview("path_to_a_file.wav")
```

If these examples doesn't work on your system, it's likely because the sox installation on Windows doesn't come with the `play` binary. If so, please let me know!

**Comment by tkamaal** [comment]
Thank you @rabitt !

**Comment by jgmgoncalves** [comment]
> If these examples doesn't work on your system, it's likely because the sox installation on Windows doesn't come with the play binary. If so, please let me know!

Hi! I'm facing a similar problem where anytime I use preview on Windows, I get the following error, even though the file path is correct:
"OSError: Play failed! [WinError 2] System could not find the specified file"

Is it possible to get the `play` binary for Windows?
Thanks!

**Comment by rabitt** [comment]
@jgmgoncalves can you check if you're able to run `play filename.wav` from a terminal window on your system, or if this is a sox specific problem?

Linking to this forum which is relevant: https://sourceforge.net/p/sox/mailman/message/28683080/

If this is a persistent problem for windows users, we can test swapping the shell to `play` with `sox` and the `-d` flag.
