### ISSUE TITLE
Combining a single file

### ISSUE THREAD

**Issue by manuelhuber** [rabitt/pysox#72]
Hello,

I'd like to use the `-v` (Combination) command on a single file. While this may seem like nonsense it's an easy way to change the volume of a file by a given percentage, like this:
`sox -v 0.9 in.wav out.wav`
Currently this is not possible since `validate_input_file_list` in the `file_info.py` raises an error when the list has less than 2 items. 

While this helps people avoid mistakes it also prevents some functionality. Do you think it is worth removing?

**Comment by justinsalamon** [comment]
cf #24
