### ISSUE TITLE
soxi inaccessible from Windows command line

### ISSUE THREAD

**Issue by lostanlen** [rabitt/pysox#73]
Dear pysox people,
My BirdVox intern (Elizabeth Mendoza) was trying to use scaper on her Windows machine today and scaper produced an error while calling 
`source_duration = sox.file_info.duration(source_file)`

At the back of the trace was something like
`Command 'soxi -D "C:\Users\User\path\to\file.wav"' returned non-zero exit status 1`

In the meanwhile, running the demo code of pysox worked perfectly.
Therefore, pysox could read and write data (using the sox command) but not read metadata (using the soxi command).

We realized that this was because neither of the two was in the Windows command prompt path.
My hacky solution was to:
1. manually add sox to path (in My Computer / Properties / ...)
2. duplicate the `sox.exe` on the same folder and call it `soxi.exe`
3. restart python, so that the %PATH% global variable would be updated

It would be good to document this problem or offer a more elegant fix to Windows users.

@justinsalamon asked for being tagged on that issue, so that's it: Justin, you're tagged now :)

**Comment by justinsalamon** [comment]
Cheers for the tag @lostanlen :)

I just noticed this was already reported in #40 , with a proposed fix that seems to work. @lostanlen feel like making a PR?
