### ISSUE TITLE
Return None rather than 0 when file info (bit rate, duration, etc. ) is NA

### ISSUE THREAD

**Issue by lostanlen** [rabitt/pysox#78]
There is a number of soxi functions that have special return values if the info is unavailable of not applicable. Here's the current behavior of pysox functions in these cases:
* `bitrate`: zero
* `comments`: empty string
* `duration`: zero
* `num_samples`: zero

In an offline conversation with @rabitt, we figured that it would be good to use the `None` constant in Python to express this kind of value. That will break type stability, but on the other hand it will help catching bugs such as
`if duration < max_duration`
or
`if bitrate < 128000`

which really should not return `True` if these values are NA. In addition, pysox currently raises a warning in those cases, so the loss in speed incurred by the lack of type stability is negligible in front of the loss in speed incurred by raising a warning, I suppose.

Thoughts?

**Comment by rabitt** [comment]
+1 - This should probably be changed along with #75, since #75 uses this new convention. I don't mind if both this issue and #68 get addressed in one PR.

**Comment by lostanlen** [comment]
OK, then I'm going to push more commits to #75 in order to close both #68 and this

**Comment by lostanlen** [comment]
#75 is ready to merge. I changed the return type of `bitrate`, `bitdepth`, `duration`,  and `num_samples`. However I did not replace empty strings in `comments` by `None` values, so `comments` will keep returning strings no matter what. I don't think anyone will use the empty string in `comments` to denote any sort of information about the audio file at hand
