### ISSUE TITLE
Base call to SoX uses shell=True in subprocess call

### ISSUE THREAD

**Issue by rabitt** [rabitt/pysox#79]
Filenames with wildcards have always behaved inconsistently with pysox. Looking into this more closely, found that - the SoX command arguments being passed to the shell rather than to the binary directly.

Thanks @jongwook for finding the source!

**Comment by lostanlen** [comment]
The LoCs at stake are:

in `sox`
https://github.com/rabitt/pysox/blob/master/sox/core.py#L51

in `soxi`
https://github.com/rabitt/pysox/blob/master/sox/core.py#L128

**Comment by rabitt** [comment]
@lostanlen unfortunately it's a change that creates cascading changes all over the library. Working on it now.
