### ISSUE TITLE
Feature Request: Add call to stats?

### ISSUE THREAD

**Issue by debswade** [rabitt/pysox#87]
The file_info.stat does not accommodate the flag to pull the RMS info.  Specifically I'm looking for Pk lev dB and RMS lev dB stats.
Using a command line sox I am able to get this using:
blah/Renders $ sox file.wav -n stats
DC offset  -0.000269
Min level  -0.482314
Max level   0.482314
Pk lev dB      -6.33
RMS lev dB    -19.81
RMS Pk dB      -9.64
RMS Tr dB     -64.27
Crest factor    4.72
Flat factor    14.31
Pk count       29.8k
Bit-depth      23/24
Num samples    69.8M
Length s    1582.727
Scale max   1.000000
Window s       0.050

Any possibility of adding a call to stats?

**Comment by rabitt** [comment]
Hi @debswade ! It's true that currently pysox implements `sox.file_info.stat` but not `sox.file_info.stats`. 

A workaround for now is to call `stats` using the `Transformer` class:

```python
import sox
tfm = sox.Transformer()
tfm.stats("file.wav")
> {'Bit-depth': '17/17',
  'Crest factor': '13.41',
  'DC offset': '0.000004',
  'Flat factor': '0.00',
  'Length s': '102.959',
  'Max level': '0.591125',
  'Min level': '-0.613373',
  'Num samples': '4.54M',
  'Pk count': '2',
  'Pk lev dB': '-4.25',
  'RMS Pk dB': '-17.91',
  'RMS Tr dB': '-69.87',
  'RMS lev dB': '-26.79',
  'Scale max': '1.000000',
  'Window s': '0.050'}
```
