### ISSUE TITLE
Can someone please provide an example of how to record audio

### ISSUE THREAD

**Issue by carylewis** [rabitt/pysox#88]
I would like to be able to do the following using the sox python library:

sox -d -t mp3 test.mp3 trim 0 00:10

I figured it out...

```
import sox

args = ['-d', '-t', 'mp3', 'test2.mp3','trim','0','00:05']

sox.core.sox(args)

````

**Comment by lostanlen** [comment]
Hello @carylewis, glad to see you've figured it out. Can we close this issue?

**Comment by carylewis** [comment]
Yes. Thanks. 

One quick question- the sox executable is required, but I thought that the python module was a wrapper around the Sox library?
