### ISSUE TITLE
This install of SoX cannot process .MP3 files.

### ISSUE THREAD

**Issue by tracek** [rabitt/pysox#91]
Hi - I am on Ubuntu 18.04. When I try to interact via Python bindings with SoX, I get a warning saying `This install of SoX cannot process .MP3 files.` And then the file is processed just fine. After looking into this issue, I have found that the root cause is in capitalization of file extension that I have on my files.

What do you think about PR to ignore letter size when checking for valid formats?

**Comment by Lextor99** [comment]
Use 
`sudo apt-get install sox libsox-fmt-mp3`

**Comment by Bug-Reaper** [comment]
Hey just a heads up. For Arch Linux you can fix this error with
```sudo pacman -S libid3tag libmad twolame```
And boom .mp3 support :)
