### ISSUE TITLE
pysox transformer modify the spectrogram value

### ISSUE THREAD

**Issue by tsungruihon** [rabitt/pysox#97]
It seems that even i just use `pysox`'s `transform` with nothing other action, some value in spectrogram seem be removed also.

```
class Equalizer:
    def __init__(self):
        self.tfm = sox.Transformer()

    def bass_and_treble(self, input_path, output_path):
        self.tfm.build(input_path, output_path)
        return output_path

```
<img width="1017" alt="Screen Shot 2019-07-19 at 3 00 59 PM" src="https://user-images.githubusercontent.com/11624203/61515905-4be89380-aa36-11e9-8b06-bf5a1ac46133.png">
<img width="993" alt="Screen Shot 2019-07-19 at 3 02 05 PM" src="https://user-images.githubusercontent.com/11624203/61515907-4c812a00-aa36-11e9-8219-7eb3198e79e6.png">

**Comment by lostanlen** [comment]
Hello @tsungruihon. How are you computing the spectrogram? With `librosa`? If so, are you using `librosa.load`? If so, note that librosa's default is to resample to 22050 Hz:
https://github.com/librosa/librosa/issues/509

**Comment by lostanlen** [comment]
I am going to close this issue unless i hear back from the OP

**Comment by tsungruihon** [comment]
@lostanlen thanks a lot. I will check it and reply you as soon as possible
