### ISSUE TITLE
Installing pysox on anaconda

### ISSUE THREAD

**Issue by edvermeire** [rabitt/pysox#98]
I'm having trouble installing pysox on Anaconda. Does anyone have instructions for how they have done it?

**Comment by lostanlen** [comment]
Create a conda environment:
`conda create -n pysoxenv` (replace pysoxenv by your favorite name)

Activate it:
`conda activate birdvoxpaint`

Install pip:
`conda install pip`

Install pysox with pip
`pip install git+https://github.com/rabitt/pysox.git`


I hope this helps!

**Comment by edvermeire** [comment]
> Create a conda environment:
> `conda create -n pysoxenv` (replace pysoxenv by your favorite name)
> 
> Activate it:
> `conda activate birdvoxpaint`
> 
> Install pip:
> `conda install pip`
> 
> Install pysox with pip
> `pip install git+https://github.com/rabitt/pysox.git`
> 
> I hope this helps!

it looks like this is the right solutions however I get an error on the last step because it cannot find git. I installed git using the instructions here: https://anaconda.org/anaconda/git

![image](https://user-images.githubusercontent.com/53376839/63063370-5cbbe600-beca-11e9-9cc0-a0042781c586.png)

**Comment by lostanlen** [comment]
Hello @edvermeire. I would suggest that you install the GitHub desktop client for Windows. It comes bundled with a git command-line utility.
Alternatively, you can download git only (without the GitHub desktop client) at this address: https://git-scm.com/download/win
